//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `MiraLaser.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <MiraLaser.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompMiraLaser_LaserReporter_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMiraLaser::LaserReporter"
};
const ::std::string iceC_RoboCompMiraLaser_LaserReporter_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "toggleLaserReport"
};
const ::std::string iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name = "toggleLaserReport";

const ::std::string iceC_RoboCompMiraLaser_Laser_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMiraLaser::Laser"
};
const ::std::string iceC_RoboCompMiraLaser_Laser_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "reportLaserData"
};
const ::std::string iceC_RoboCompMiraLaser_Laser_reportLaserData_name = "reportLaserData";

}

bool
RoboCompMiraLaser::LaserReporter::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMiraLaser_LaserReporter_ids, iceC_RoboCompMiraLaser_LaserReporter_ids + 2, s);
}

::std::vector<::std::string>
RoboCompMiraLaser::LaserReporter::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompMiraLaser_LaserReporter_ids[0], &iceC_RoboCompMiraLaser_LaserReporter_ids[2]);
}

::std::string
RoboCompMiraLaser::LaserReporter::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMiraLaser::LaserReporter::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompMiraLaser::LaserReporter";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompMiraLaser::LaserReporter::_iceD_toggleLaserReport(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    bool iceP_enable;
    istr->readAll(iceP_enable);
    inS.endReadParams();
    this->toggleLaserReport(iceP_enable, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompMiraLaser::LaserReporter::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMiraLaser_LaserReporter_ops, iceC_RoboCompMiraLaser_LaserReporter_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMiraLaser_LaserReporter_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_toggleLaserReport(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
RoboCompMiraLaser::Laser::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMiraLaser_Laser_ids, iceC_RoboCompMiraLaser_Laser_ids + 2, s);
}

::std::vector<::std::string>
RoboCompMiraLaser::Laser::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompMiraLaser_Laser_ids[0], &iceC_RoboCompMiraLaser_Laser_ids[2]);
}

::std::string
RoboCompMiraLaser::Laser::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMiraLaser::Laser::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompMiraLaser::Laser";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompMiraLaser::Laser::_iceD_reportLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    LaserDataT iceP_data;
    istr->readAll(iceP_data);
    inS.endReadParams();
    this->reportLaserData(::std::move(iceP_data), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompMiraLaser::Laser::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMiraLaser_Laser_ops, iceC_RoboCompMiraLaser_Laser_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMiraLaser_Laser_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_reportLaserData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMiraLaser::LaserReporterPrx::_iceI_toggleLaserReport(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, bool iceP_enable, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_enable);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompMiraLaser::LaserReporterPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LaserReporterPrx>();
}
/// \endcond

const ::std::string&
RoboCompMiraLaser::LaserReporterPrx::ice_staticId()
{
    return LaserReporter::ice_staticId();
}

/// \cond INTERNAL
void
RoboCompMiraLaser::LaserPrx::_iceI_reportLaserData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const LaserDataT& iceP_data, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompMiraLaser_Laser_reportLaserData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_data);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompMiraLaser::LaserPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LaserPrx>();
}
/// \endcond

const ::std::string&
RoboCompMiraLaser::LaserPrx::ice_staticId()
{
    return Laser::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name = "toggleLaserReport";

const ::std::string iceC_RoboCompMiraLaser_Laser_reportLaserData_name = "reportLaserData";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompMiraLaser::upCast(LaserReporter* p) { return p; }

void
::IceProxy::RoboCompMiraLaser::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< LaserReporter>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new LaserReporter;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompMiraLaser::LaserReporter::_iceI_begin_toggleLaserReport(bool iceP_enable, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_enable);
        result->endWriteParams();
        result->invoke(iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompMiraLaser::LaserReporter::end_toggleLaserReport(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompMiraLaser_LaserReporter_toggleLaserReport_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompMiraLaser::LaserReporter::_newInstance() const
{
    return new LaserReporter;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompMiraLaser::LaserReporter::ice_staticId()
{
    return ::RoboCompMiraLaser::LaserReporter::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompMiraLaser::upCast(Laser* p) { return p; }

void
::IceProxy::RoboCompMiraLaser::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Laser>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Laser;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompMiraLaser::Laser::_iceI_begin_reportLaserData(const ::RoboCompMiraLaser::LaserDataT& iceP_data, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompMiraLaser_Laser_reportLaserData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompMiraLaser_Laser_reportLaserData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_data);
        result->endWriteParams();
        result->invoke(iceC_RoboCompMiraLaser_Laser_reportLaserData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompMiraLaser::Laser::end_reportLaserData(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompMiraLaser_Laser_reportLaserData_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompMiraLaser::Laser::_newInstance() const
{
    return new Laser;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompMiraLaser::Laser::ice_staticId()
{
    return ::RoboCompMiraLaser::Laser::ice_staticId();
}

RoboCompMiraLaser::LaserReporter::~LaserReporter()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompMiraLaser::upCast(LaserReporter* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompMiraLaser_LaserReporter_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMiraLaser::LaserReporter"
};

}

bool
RoboCompMiraLaser::LaserReporter::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMiraLaser_LaserReporter_ids, iceC_RoboCompMiraLaser_LaserReporter_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompMiraLaser::LaserReporter::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompMiraLaser_LaserReporter_ids[0], &iceC_RoboCompMiraLaser_LaserReporter_ids[2]);
}

const ::std::string&
RoboCompMiraLaser::LaserReporter::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMiraLaser::LaserReporter::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompMiraLaser::LaserReporter";
    return typeId;
#else
    return iceC_RoboCompMiraLaser_LaserReporter_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompMiraLaser::LaserReporter::_iceD_toggleLaserReport(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    bool iceP_enable;
    istr->read(iceP_enable);
    inS.endReadParams();
    this->toggleLaserReport(iceP_enable, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompMiraLaser_LaserReporter_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "toggleLaserReport"
};

}

/// \cond INTERNAL
bool
RoboCompMiraLaser::LaserReporter::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMiraLaser_LaserReporter_all, iceC_RoboCompMiraLaser_LaserReporter_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMiraLaser_LaserReporter_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_toggleLaserReport(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompMiraLaser::LaserReporter::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< LaserReporter, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompMiraLaser::LaserReporter::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< LaserReporter, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMiraLaser::_icePatchObjectPtr(LaserReporterPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LaserReporterPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(LaserReporter::ice_staticId(), v);
    }
}
/// \endcond

RoboCompMiraLaser::Laser::~Laser()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompMiraLaser::upCast(Laser* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompMiraLaser_Laser_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMiraLaser::Laser"
};

}

bool
RoboCompMiraLaser::Laser::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMiraLaser_Laser_ids, iceC_RoboCompMiraLaser_Laser_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompMiraLaser::Laser::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompMiraLaser_Laser_ids[0], &iceC_RoboCompMiraLaser_Laser_ids[2]);
}

const ::std::string&
RoboCompMiraLaser::Laser::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMiraLaser::Laser::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompMiraLaser::Laser";
    return typeId;
#else
    return iceC_RoboCompMiraLaser_Laser_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompMiraLaser::Laser::_iceD_reportLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    LaserDataT iceP_data;
    istr->read(iceP_data);
    inS.endReadParams();
    this->reportLaserData(iceP_data, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompMiraLaser_Laser_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "reportLaserData"
};

}

/// \cond INTERNAL
bool
RoboCompMiraLaser::Laser::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMiraLaser_Laser_all, iceC_RoboCompMiraLaser_Laser_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMiraLaser_Laser_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_reportLaserData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompMiraLaser::Laser::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Laser, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompMiraLaser::Laser::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Laser, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMiraLaser::_icePatchObjectPtr(LaserPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LaserPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Laser::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
