// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `personFollower.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <personFollower.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboComppersonFollower_personFollower_ids[2] =
{
    "::Ice::Object",
    "::RoboComppersonFollower::personFollower"
};
const ::std::string iceC_RoboComppersonFollower_personFollower_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "personLost",
    "updatePersonPose"
};
const ::std::string iceC_RoboComppersonFollower_personFollower_updatePersonPose_name = "updatePersonPose";
const ::std::string iceC_RoboComppersonFollower_personFollower_personLost_name = "personLost";

}

bool
RoboComppersonFollower::personFollower::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboComppersonFollower_personFollower_ids, iceC_RoboComppersonFollower_personFollower_ids + 2, s);
}

::std::vector<::std::string>
RoboComppersonFollower::personFollower::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboComppersonFollower_personFollower_ids[0], &iceC_RoboComppersonFollower_personFollower_ids[2]);
}

::std::string
RoboComppersonFollower::personFollower::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboComppersonFollower::personFollower::ice_staticId()
{
    static const ::std::string typeId = "::RoboComppersonFollower::personFollower";
    return typeId;
}

bool
RoboComppersonFollower::personFollower::_iceD_updatePersonPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboComppersonFollower::Pose iceP_p;
    istr->readAll(iceP_p);
    inS.endReadParams();
    this->updatePersonPose(::std::move(iceP_p), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboComppersonFollower::personFollower::_iceD_personLost(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->personLost(current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboComppersonFollower::personFollower::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboComppersonFollower_personFollower_ops, iceC_RoboComppersonFollower_personFollower_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboComppersonFollower_personFollower_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_personLost(in, current);
        }
        case 5:
        {
            return _iceD_updatePersonPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboComppersonFollower::personFollowerPrx::_iceI_updatePersonPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboComppersonFollower::Pose& iceP_p, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboComppersonFollower_personFollower_updatePersonPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_p);
        },
        nullptr);
}

void
RoboComppersonFollower::personFollowerPrx::_iceI_personLost(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboComppersonFollower_personFollower_personLost_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboComppersonFollower::personFollowerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<personFollowerPrx>();
}

const ::std::string&
RoboComppersonFollower::personFollowerPrx::ice_staticId()
{
    return RoboComppersonFollower::personFollower::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboComppersonFollower_personFollower_updatePersonPose_name = "updatePersonPose";

const ::std::string iceC_RoboComppersonFollower_personFollower_personLost_name = "personLost";

}
::IceProxy::Ice::Object* ::IceProxy::RoboComppersonFollower::upCast(::IceProxy::RoboComppersonFollower::personFollower* p) { return p; }

void
::IceProxy::RoboComppersonFollower::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboComppersonFollower::personFollower>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboComppersonFollower::personFollower;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboComppersonFollower::personFollower::_iceI_begin_updatePersonPose(const ::RoboComppersonFollower::Pose& iceP_p, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboComppersonFollower_personFollower_updatePersonPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboComppersonFollower_personFollower_updatePersonPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_p);
        result->endWriteParams();
        result->invoke(iceC_RoboComppersonFollower_personFollower_updatePersonPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboComppersonFollower::personFollower::end_updatePersonPose(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboComppersonFollower_personFollower_updatePersonPose_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboComppersonFollower::personFollower::_iceI_begin_personLost(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboComppersonFollower_personFollower_personLost_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboComppersonFollower_personFollower_personLost_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboComppersonFollower_personFollower_personLost_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboComppersonFollower::personFollower::end_personLost(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboComppersonFollower_personFollower_personLost_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboComppersonFollower::personFollower::_newInstance() const
{
    return new personFollower;
}

const ::std::string&
IceProxy::RoboComppersonFollower::personFollower::ice_staticId()
{
    return ::RoboComppersonFollower::personFollower::ice_staticId();
}

RoboComppersonFollower::personFollower::~personFollower()
{
}

::Ice::Object* RoboComppersonFollower::upCast(::RoboComppersonFollower::personFollower* p) { return p; }


namespace
{
const ::std::string iceC_RoboComppersonFollower_personFollower_ids[2] =
{
    "::Ice::Object",
    "::RoboComppersonFollower::personFollower"
};

}

bool
RoboComppersonFollower::personFollower::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboComppersonFollower_personFollower_ids, iceC_RoboComppersonFollower_personFollower_ids + 2, s);
}

::std::vector< ::std::string>
RoboComppersonFollower::personFollower::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboComppersonFollower_personFollower_ids[0], &iceC_RoboComppersonFollower_personFollower_ids[2]);
}

const ::std::string&
RoboComppersonFollower::personFollower::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboComppersonFollower::personFollower::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboComppersonFollower::personFollower";
    return typeId;
#else
    return iceC_RoboComppersonFollower_personFollower_ids[1];
#endif
}

bool
RoboComppersonFollower::personFollower::_iceD_updatePersonPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboComppersonFollower::Pose iceP_p;
    istr->read(iceP_p);
    inS.endReadParams();
    this->updatePersonPose(iceP_p, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboComppersonFollower::personFollower::_iceD_personLost(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->personLost(current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboComppersonFollower_personFollower_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "personLost",
    "updatePersonPose"
};

}

bool
RoboComppersonFollower::personFollower::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboComppersonFollower_personFollower_all, iceC_RoboComppersonFollower_personFollower_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboComppersonFollower_personFollower_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_personLost(in, current);
        }
        case 5:
        {
            return _iceD_updatePersonPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboComppersonFollower::personFollower::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboComppersonFollower::personFollower, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboComppersonFollower::personFollower::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboComppersonFollower::personFollower, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboComppersonFollower::_icePatchObjectPtr(personFollowerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboComppersonFollower::personFollowerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboComppersonFollower::personFollower::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
